"""initial_phase2_tables

Revision ID: d74ef82fab04
Revises: 
Create Date: 2026-08-03 23:30:09.145793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74ef82fab04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_id'), 'execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_execution_logs_run_id'), 'execution_logs', ['run_id'], unique=False)
    op.create_index('ix_execution_logs_run_step', 'execution_logs', ['run_id', 'step_index'], unique=False)
    op.create_index('ix_execution_logs_started_at', 'execution_logs', ['started_at'], unique=False)
    op.create_index('ix_execution_logs_status', 'execution_logs', ['status'], unique=False)
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('actions_json', sa.Text(), nullable=False),
    sa.Column('params_schema_json', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_id'), 'plugins', ['id'], unique=False)
    op.create_index('ix_plugins_is_builtin', 'plugins', ['is_builtin'], unique=False)
    op.create_index('ix_plugins_is_enabled', 'plugins', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_plugins_plugin_id'), 'plugins', ['plugin_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash_bcrypt', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_run_id'), 'notifications', ['run_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_connections_user_provider')
    )
    op.create_index(op.f('ix_oauth_connections_id'), 'oauth_connections', ['id'], unique=False)
    op.create_index('ix_oauth_connections_is_active', 'oauth_connections', ['is_active'], unique=False)
    op.create_index('ix_oauth_connections_provider', 'oauth_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_connections_user_id'), 'oauth_connections', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_info', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_secrets_user_name')
    )
    op.create_index(op.f('ix_secrets_id'), 'secrets', ['id'], unique=False)
    op.create_index('ix_secrets_user_active', 'secrets', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_secrets_user_id'), 'secrets', ['user_id'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('preview_image_url', sa.String(length=512), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_author_id'), 'workflow_templates', ['author_id'], unique=False)
    op.create_index('ix_workflow_templates_category', 'workflow_templates', ['category'], unique=False)
    op.create_index('ix_workflow_templates_featured', 'workflow_templates', ['is_featured'], unique=False)
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_index('ix_workflow_templates_use_count', 'workflow_templates', ['use_count'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('natural_language_request', sa.Text(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_category', 'workflows', ['category'], unique=False)
    op.create_index('ix_workflows_created_at', 'workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_index('ix_workflows_is_public', 'workflows', ['is_public'], unique=False)
    op.create_index('ix_workflows_user_active', 'workflows', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('misfire_policy', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_active_next_run', 'schedules', ['is_active', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_schedules_workflow_id'), 'schedules', ['workflow_id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_history_action', 'workflow_history', ['action'], unique=False)
    op.create_index('ix_workflow_history_created_at', 'workflow_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_history_id'), 'workflow_history', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_history_user_id'), 'workflow_history', ['user_id'], unique=False)
    op.create_index('ix_workflow_history_workflow_created', 'workflow_history', ['workflow_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workflow_history_workflow_id'), 'workflow_history', ['workflow_id'], unique=False)
    op.create_table('workflow_marketplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketplace_approved', 'workflow_marketplace', ['is_approved'], unique=False)
    op.create_index('ix_marketplace_downloads', 'workflow_marketplace', ['downloads'], unique=False)
    op.create_index('ix_marketplace_price', 'workflow_marketplace', ['price'], unique=False)
    op.create_index('ix_marketplace_rating_avg', 'workflow_marketplace', ['rating_avg'], unique=False)
    op.create_index(op.f('ix_workflow_marketplace_id'), 'workflow_marketplace', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_marketplace_user_id'), 'workflow_marketplace', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_marketplace_workflow_id'), 'workflow_marketplace', ['workflow_id'], unique=True)
    op.create_table('workflow_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=128), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_shares_expires_at', 'workflow_shares', ['expires_at'], unique=False)
    op.create_index(op.f('ix_workflow_shares_id'), 'workflow_shares', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_shares_owner_id'), 'workflow_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workflow_shares_share_token'), 'workflow_shares', ['share_token'], unique=True)
    op.create_index(op.f('ix_workflow_shares_shared_with_user_id'), 'workflow_shares', ['shared_with_user_id'], unique=False)
    op.create_index('ix_workflow_shares_workflow_active', 'workflow_shares', ['workflow_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflow_shares_workflow_id'), 'workflow_shares', ['workflow_id'], unique=False)
    op.create_table('workflow_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'name', name='uq_workflow_variables_workflow_name')
    )
    op.create_index(op.f('ix_workflow_variables_id'), 'workflow_variables', ['id'], unique=False)
    op.create_index('ix_workflow_variables_is_secret', 'workflow_variables', ['is_secret'], unique=False)
    op.create_index(op.f('ix_workflow_variables_workflow_id'), 'workflow_variables', ['workflow_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version_number', name='uq_workflow_versions_workflow_version')
    )
    op.create_index(op.f('ix_workflow_versions_created_by'), 'workflow_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_workflow_versions_id'), 'workflow_versions', ['id'], unique=False)
    op.create_index('ix_workflow_versions_workflow_current', 'workflow_versions', ['workflow_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    op.create_table('marketplace_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['workflow_marketplace.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace_id', 'reviewer_id', name='uq_marketplace_reviews_listing_reviewer')
    )
    op.create_index(op.f('ix_marketplace_reviews_id'), 'marketplace_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_reviews_marketplace_id'), 'marketplace_reviews', ['marketplace_id'], unique=False)
    op.create_index('ix_marketplace_reviews_rating', 'marketplace_reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_marketplace_reviews_reviewer_id'), 'marketplace_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_reviews_reviewer_id'), table_name='marketplace_reviews')
    op.drop_index('ix_marketplace_reviews_rating', table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_marketplace_id'), table_name='marketplace_reviews')
    op.drop_index(op.f('ix_marketplace_reviews_id'), table_name='marketplace_reviews')
    op.drop_table('marketplace_reviews')
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_index('ix_workflow_versions_workflow_current', table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_created_by'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_variables_workflow_id'), table_name='workflow_variables')
    op.drop_index('ix_workflow_variables_is_secret', table_name='workflow_variables')
    op.drop_index(op.f('ix_workflow_variables_id'), table_name='workflow_variables')
    op.drop_table('workflow_variables')
    op.drop_index(op.f('ix_workflow_shares_workflow_id'), table_name='workflow_shares')
    op.drop_index('ix_workflow_shares_workflow_active', table_name='workflow_shares')
    op.drop_index(op.f('ix_workflow_shares_shared_with_user_id'), table_name='workflow_shares')
    op.drop_index(op.f('ix_workflow_shares_share_token'), table_name='workflow_shares')
    op.drop_index(op.f('ix_workflow_shares_owner_id'), table_name='workflow_shares')
    op.drop_index(op.f('ix_workflow_shares_id'), table_name='workflow_shares')
    op.drop_index('ix_workflow_shares_expires_at', table_name='workflow_shares')
    op.drop_table('workflow_shares')
    op.drop_index(op.f('ix_workflow_marketplace_workflow_id'), table_name='workflow_marketplace')
    op.drop_index(op.f('ix_workflow_marketplace_user_id'), table_name='workflow_marketplace')
    op.drop_index(op.f('ix_workflow_marketplace_id'), table_name='workflow_marketplace')
    op.drop_index('ix_marketplace_rating_avg', table_name='workflow_marketplace')
    op.drop_index('ix_marketplace_price', table_name='workflow_marketplace')
    op.drop_index('ix_marketplace_downloads', table_name='workflow_marketplace')
    op.drop_index('ix_marketplace_approved', table_name='workflow_marketplace')
    op.drop_table('workflow_marketplace')
    op.drop_index(op.f('ix_workflow_history_workflow_id'), table_name='workflow_history')
    op.drop_index('ix_workflow_history_workflow_created', table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_user_id'), table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_id'), table_name='workflow_history')
    op.drop_index('ix_workflow_history_created_at', table_name='workflow_history')
    op.drop_index('ix_workflow_history_action', table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_schedules_workflow_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index('ix_schedules_active_next_run', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index('ix_workflows_user_active', table_name='workflows')
    op.drop_index('ix_workflows_is_public', table_name='workflows')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_index('ix_workflows_created_at', table_name='workflows')
    op.drop_index('ix_workflows_category', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_workflow_templates_use_count', table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_index('ix_workflow_templates_featured', table_name='workflow_templates')
    op.drop_index('ix_workflow_templates_category', table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_author_id'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_secrets_user_id'), table_name='secrets')
    op.drop_index('ix_secrets_user_active', table_name='secrets')
    op.drop_index(op.f('ix_secrets_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_oauth_connections_user_id'), table_name='oauth_connections')
    op.drop_index('ix_oauth_connections_provider', table_name='oauth_connections')
    op.drop_index('ix_oauth_connections_is_active', table_name='oauth_connections')
    op.drop_index(op.f('ix_oauth_connections_id'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index(op.f('ix_notifications_run_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plugins_plugin_id'), table_name='plugins')
    op.drop_index('ix_plugins_is_enabled', table_name='plugins')
    op.drop_index('ix_plugins_is_builtin', table_name='plugins')
    op.drop_index(op.f('ix_plugins_id'), table_name='plugins')
    op.drop_table('plugins')
    op.drop_index('ix_execution_logs_status', table_name='execution_logs')
    op.drop_index('ix_execution_logs_started_at', table_name='execution_logs')
    op.drop_index('ix_execution_logs_run_step', table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_run_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    # ### end Alembic commands ###
